# Setup
title:            Curious Mustard
# tagline:          'A Jekyll theme'
description:      'A blog I suppose'
url:              https://curiousmustard.github.io/
baseurl:          ''
paginate:         5

# About and contact
author:
  name:           'Jen Hubbard'
  url:            https://twitter.com/curiousmustard.com

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

# Custom vars
version:          3.0.0
