# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty


# Setup
title:            Curious Mustard
# tagline:          'A Jekyll theme'
description:      'A blog I suppose'
url:              https://curiousmustard.github.io/
baseurl:          /

author:
  name:           'Jen Hubbard'
  url:            https://twitter.com/curiousmustard

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/curiousmustard/curiousmustard.github.io
